name: Windows MSVC x64

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'

permissions:
  contents: write

env:
  VCPKG_FEATURE_FLAGS: dependencygraph
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-publish:
    runs-on: windows-latest
    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore ProjectZ.sln

    - name: Build Project
      run: msbuild /p:Configuration=Release /t:Build

    - name: Publish Project (with settings from screenshot)
      run: |
        mkdir publish
        
        msbuild /t:Publish /p:Configuration=Release `
                /p:TargetFramework=net8.0-windows `
                /p:RuntimeIdentifier=win-x64 `
                /p:SelfContained=false `
                /p:PublishSingleFile=true `
                /p:EnableReadyToRun=true `
                /p:PublishDir=$(System.DefaultWorkingDirectory)\publish `
                ProjectZ.csproj

        Remove-Item -Path "publish\*.pdb" -ErrorAction SilentlyContinue
        Remove-Item -Path "publish\*.xml" -ErrorAction SilentlyContinue

    - name: List published files
      run: dir /s publish

    - name: Upload publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Links-Awakening-DX-HD-RUS
        path: publish
