name: Windows MSVC x64

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'

permissions:
  contents: write

env:
  VCPKG_FEATURE_FLAGS: dependencygraph
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore ProjectZ.sln

    - name: Build Project
      run: msbuild /p:Configuration=Release /t:Build

    - name: Build Project
      run: msbuild /p:Configuration=Release /t:Build

    - name: Publish Project (Clean Output)
      run: |
        # Создаем чистую папку для публикации
        mkdir publish
        # Копируем только необходимые файлы
        cp bin/Release/net8.0-windows/*.exe publish/
        cp bin/Release/net8.0-windows/*.dll publish/
        # Удаляем ненужные файлы (настройте под ваш проект)
        rm -rf publish/*.pdb
        rm -rf publish/*.xml
        rm -rf publish/runtimes

    - name: List publish directory contents
      run: ls -R publish

    - name: Archive published artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Links-Awakening-DX-HD-RUS
        path: publish
